apiVersion: apps/v1
kind: Deployment
metadata:
  name: tic-tac-toe
  labels:
    app: tic-tac-toe
spec:
  replicas: 3
  selector:
    matchLabels:
      app: tic-tac-toe
  template:
    metadata:
      labels:
        app: tic-tac-toe
    spec:
      containers:
        - name: tic-tac-toe
          image: "{{ .Values.tic-tac-toe.image.repo }}:{{ .Values.tic-tac-toe.image.version }}"
          imagePullPolicy: {{ .Values.tic-tac-toe.image.pullPolicy }}
          ports:
            - containerPort: 80
          resources:
            {{- toYaml .Values.tic-tac-toe.resources | nindent 12 }}
          livenessProbe:
            httpGet:
              path: {{ .Values.tic-tac-toe.livenessProbe.path }}
              port: {{ .Values.tic-tac-toe.livenessProbe.port }}
            initialDelaySeconds: {{ .Values.tic-tac-toe.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.tic-tac-toe.livenessProbe.periodSeconds }}
          readinessProbe:
            httpGet:
              path: {{ .Values.tic-tac-toe.readinessProbe.path }}
              port: {{ .Values.tic-tac-toe.readinessProbe.port }}
            initialDelaySeconds: {{ .Values.tic-tac-toe.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.tic-tac-toe.readinessProbe.periodSeconds }}
      imagePullSecrets:
        {{- toYaml .Values.tic-tac-toe.imagePullSecrets | nindent 8 }}
