apiVersion: v1
kind: Service
metadata:
  name: {{ include "tic-tac-toe.fullname" . }}
  labels:
    {{- include "tic-tac-toe.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 80
      protocol: TCP
      name: http
  selector:
    {{- toYaml .Values.appLabels | nindent 4 }}
