apiVersion: v1
kind: Service
metadata:
  name: tic-tac-toe
  labels:
    {{- toYaml .Values.ticTacToe.appLabels | nindent 4 }}
spec:
  type: {{ .Values.ticTacToe.service.type }}
  ports:
    - port: {{ .Values.ticTacToe.service.port }}
      targetPort: 80
      protocol: TCP
      name: http
  selector:
    {{- toYaml .Values.ticTacToe.appLabels | nindent 4 }}
