apiVersion: v1
kind: Service
metadata:
  name: tic-tac-toe
  labels:
    tic-tac-toe
spec:
  type: {{ .Values.ticTacToe.service.type }}
  ports:
    - port: {{ .Values.ticTacToe.service.port }}
      targetPort: 80
      protocol: TCP
      name: http
  selector:
    tic-tac-toe
