ticTacToe:
  image:
    repo: 851725549954.dkr.ecr.us-east-1.amazonaws.com/tic-tac-toe
    version: 65
    pullPolicy: IfNotPresent

  service:
    type: ClusterIP
    port: 80

  resources:
    limits:
      cpu: "0.5"
      memory: "512Mi"
    requests:
      cpu: "0.2"
      memory: "256Mi"

  livenessProbe:
    path: /
    port: 80
    initialDelaySeconds: 30
    periodSeconds: 10

  readinessProbe:
    path: /
    port: 80
    initialDelaySeconds: 5
    periodSeconds: 5

  appLabels:
    app: tic-tac-toe
